sudo: required
services:
  - docker
before_install:
  - docker build -t practical -f Dockerfile.dev .
script:
  - docker run practical npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "Docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-646164614672"
  bucket_path: "Docker-react"

on:
  branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"